/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.1/userguide/building_java_projects.html
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("io.freefair.lombok") version "9.5.0"
    id("net.ltgt.errorprone") version "latest.release"
}


repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation("com.google.guava:guava:32.0.1-android")
    errorprone("com.google.errorprone:error_prone_core:latest.release")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

application {
    // Define the main class for the application.
    mainClass.set(project.findProperty("chooseMain").toString())
}

testing {
    suites {
        val test by getting(JvmTestSuite::class) {
            useJUnitJupiter()
        }
    }
}

tasks.register<JavaExec>("txt") {
    group = "application"
    description = "Run the text interface"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("main.TXTmain")
    standardInput = System.`in`
}

tasks.register<JavaExec>("gui") {
    group = "application"
    description = "Run the GUI interface"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("main.GUImain")
}

tasks.withType<Javadoc> {
    exclude("**/*.png")
}